### ISSUE TITLE
Add Protected/Private impl

### ISSUE THREAD

**Issue by SK83RJOSH** [philpax/pyxis#17]
Currently all impls are public, which is fine, until you start to implement complex types purely in `pyx`.

**Comment by philpax** [comment]
Fields are implicitly made private if they start with `_`, is that sufficient for you or would you like explicit `pub` on fields?

Also, do you want impl / vftable functions to be private by default as well?

**Comment by SK83RJOSH** [comment]
Hmm, I kind of prefer private by default since pyxis is rust-like, but it's quite the change to existing definitions. That said, I guess we should do it, and functions/fields should probably be consistent. I'm also not entirely opposed to something like `internal` instead, which means we can:
- `pub(crate)` in rust
- `internal` in C#
- `__private_impl` in anything else

Or we just adopt rust syntax here, and translate rust visibilities as needed (though I suppose, no other backends are happening).

**Comment by philpax** [comment]
I've done this, but I've limited the visibility to private and public (i.e. `` and `pub` respectively). I didn't quite want to figure out what the semantics of the others should be.
