### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by philpax** [philpax/pyxis#2]
Many of the classes Pyxis is used to interface with use multiple inheritance. The fields can be manually specified, but the vtables get quite tricky to resolve. Additionally, inheritance can be resolved differently between compilers.

To begin with, Pyxis will support one inheritance "backend" - Windows VC++ - and then more support can be added in future if necessary.

Requirements: 
- Types should be able to derive from multiple types
- Each type should be automatically placed correctly based on the size of the preceding base types, but these can be overridden if the size of the bases is not exactly known
- Given that the first vtable of the derived type extends the first base type, the existing base type cannot be used verbatim; instead, all of its fields need to be imported, and a helper should be generated for casting to the base type
- Each base type should be able to have its own vtable if required
- Cast helpers should be generated for definitively casting to a base type from a derived type, and to optionally cast to a derived type from a base type
  - User integrations of generated code might be able to use their project's RTTI system to build stronger guarantees around the base->derived casts?
  - @SK83RJOSH suggested `AsRef`, seems reasonable

**Comment by philpax** [comment]
I've been thinking about this and trying to find the best solution. I don't want to be too prescriptive about how type layout plays out, but I also don't want too much magic. 

My latest thinking is that something like
```rust
type Base1 {
    my_cool_field: unknown<64>,
}
impl Base1 {
    fn frobnicate(&mut self);
}
vftable Base1 {
    fn frobnicate_virtual(&mut self);
}
type Base2 {
    my_cooler_field: unknown<128>,
}
impl Base2 {
    fn frobnicate_better(&mut self);
}
vftable Base2 {
    fn frobnicate_better_virtual(&mut self);
}
type Derived {
    #[base]
    base1: Base1,
    #[base]
    base2: Base2,
}
vftable Derived {
    #[index(3)]
    fn cool_method(&mut self);
}
```

will do multiple things:
- the fields `base1` and `base2` will be present
- a `DerivedVftable` struct is present with the methods from `Base1` and `vftable Derived`; the latter *must* start with an `index` above the size of `Base1`'s vftable to ensure that there are no conflicts
- a `vftable()` function is added that casts `base1.vftable` to `DerivedVftable`
- helper functions are generated for every virtual and member function that do all necessary casting
- cast helpers are generated

The resulting Rust code should look something like
```rust
trait AsBase<T> {
    fn as_base(&self) -> &T;
    fn as_base_mut(&mut self) -> &mut T;
}
impl<T, U: AsBase<T>> AsRef<T> for U {
    fn as_ref(&self) -> &T {
        self.as_base()
    }
}

struct Base1 {
    vftable: *const Base1Vftable,
    my_cool_field: [u8; 64],
}
struct Base1Vftable {
    frobnicate_virtual: fn(&mut Base1),
}
impl Base1 {
    fn frobnicate(&mut self) {
        // implementation
    }

    fn frobnicate_virtual(&mut self) {
        (self.vftable.frobnicate_virtual)(self)
    }
}

struct Base2 {
    vftable: *const Base2Vftable,
    my_cooler_field: [u8; 128],
}
struct Base2Vftable {
    frobnicate_better_virtual: fn(&mut Base2),
}
impl Base2 {
    fn frobnicate_better(&mut self) {
        // implementation
    }

    fn frobnicate_better_virtual(&mut self) {
        (self.vftable.frobnicate_better_virtual)(self)
    }
}

struct Derived {
    base1: Base1,
    base2: Base2,
}
struct DerivedVftable {
    frobnicate_virtual: fn(&mut Derived),
    _vfunc_1: fn(&mut Derived),
    _vfunc_2: fn(&mut Derived),
    cool_method: fn(&mut Derived),
}
impl Derived {
    fn vftable(&self) -> &DerivedVftable {
        unsafe { &*(self.base1.vftable as *const DerivedVftable) }
    }

    fn frobnicate(&mut self) {
        self.base1.frobnicate()
    }

    fn frobnicate_better(&mut self) {
        self.base2.frobnicate_better()
    }

    fn cool_method(&mut self) {
        (self.vftable().cool_method)(self)
    }
}
impl AsBase<Base1> for Derived {
    fn as_base(&self) -> &Base1 {
        &self.base1
    }
    fn as_base_mut(&mut self) -> &mut Base1 {
        &mut self.base1
    }
}
impl AsBase<Base2> for Derived {
    fn as_base(&self) -> &Base2 {
        &self.base2
    }
    fn as_base_mut(&mut self) -> &mut Base2 {
        &mut self.base2
    }
}
```

That is, marking a field as `#[base]` will cause proxy functions to be generated, `AsBase` implementations to be generated, and `vftable` to be specialised. If there are no bases, or all the bases have no vftable, there's just a regular `vftable` field. The `vftable` will be based on the first base with a vftable.

**Comment by philpax** [comment]
I haven't done this yet because I haven't figured out how all of the permutations of `{base1 vftable present, base2 vftable present, derived vftable present}` should behave. I'll need to play around with MSVC to deduce that.

Aside from that, I'm beginning to wonder if I should make `vftable` an explicit field within type structures? It's not always obvious that it'll be added to your type if you use `impl virtual`, and Pyxis is all about unambiguous type definitions.

**Comment by philpax** [comment]
Ok, from https://github.com/philpax/pyxis/blob/7d6dbcb3afff8a10349c547dab14dc7f751fe38d/layout/msvc2022/output.txt, it looks like MSVC will reorder the fields to move the base class with a vftable to the start. That's good! That justifies the decision to make layout explicit - what you have in memory is what you should be using, after all.

Hopefully shouldn't be too difficult to do now 😅

**Comment by philpax** [comment]
So I'm going with using the structs directly, with no field replacement. Instead, all virtual methods will retrieve the relevant vftable from the relevant base.

I've started implementing this by passing through the base functions to a derived type if the derived type has no vftable of its own, but support for derived types with vftables is still pending (the codegen will be wrong right now).

**Comment by SK83RJOSH** [comment]
It would also be nice if you could do the same for member functions – as it stands it gets a bit annoying to go down the struct chain to call them. 🙂

**Comment by philpax** [comment]
> It would also be nice if you could do the same for member functions – as it stands it gets a bit annoying to go down the struct chain to call them. 🙂

Yeah, that's a good idea. The codegen will need to be tweaked a bit, but I think it'd be worth it.

> But it's a bit tricky though of course, ideally we check that no conflicting signatures exist, if they do we assume they're overrides and drop the imported functions perhaps? Or require users to annotate them as such, perhaps?

Honestly, my plan was just to let them conflict for now. Once that's an issue, I'll figure out an actual solution (manual renaming, automatic renaming, an error, just not emitting the relevant base functions and forcing you to go through the base field, etc)

**Comment by philpax** [comment]
The implementation is basically done now. There's one suite of tests left to write before I close out this issue, but I think it's ready to be tested in production code!
