### ISSUE TITLE
Allow overriding default callconv on functions

### ISSUE THREAD

**Issue by SK83RJOSH** [philpax/pyxis#21]
`system` and `thiscall` are sane defaults, but sometimes we may want to override it. Perhaps even the defaults for a given project via `build.rs` or a `.pyx` file.

**Comment by philpax** [comment]
done in https://github.com/philpax/pyxis/commit/0810d34c9cd3ba93a48ed7fdd1924891a5226cf3 and https://github.com/philpax/pyxis/commit/ceac052d01cd5c1dc4556790cca9c0c7ec272647
