### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by philpax** [philpax/pyxis#24]
At present, Pyxis makes no assumptions about alignment and outputs no alignment directives for the sole Rust backend. However, this is starting to cause problems as our target game has math types that are aligned, and this isn't captured within the output.

The proposal is to:
- add alignment to type definitions (both types and enums)
- define alignments for all primitive types, matching their current sizes
- alignment is propagated to the backend
- `extern type`s can have alignment set with `#[align(N)]`.
- for enums, assume the alignment is the same as their base type
- for types:
  - assume the default alignment is the size of a pointer (I'm not sure if this is true for all architectures, but it's true for the ones we currently care about)
  - each field will use the alignment of its associated type
  - array types will use the alignment of their base type
  - the size of the type must be a multiple of the type's alignment
  - if the field's address is not a multiple of alignment, an **error will be raised**
  - if the type's alignment is less than the lowest common multiple of the alignments of the fields, an **error will be raised**, and the type's alignment must be set with `#[align(N)]`
  - if both `packed` and `align` are specified, an **error will be raised** (the previous errors will not be raised)

# Examples
## BBI
```rust
type BBI {
  bool_1: bool, // align 1
  bool_2: bool, // align 1
  int: i32, // align 4
}
```
will be rejected by default, because `int` will be placed at address 2, which 4 does not divide. This can be fixed by:
### ~~Setting type alignment~~
```rust
#[align(2)]
type BBI {
  bool_1: bool, // align 1
  bool_2: bool, // align 1
  int: i32, // align 4
}
```

This does not work: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a8abb75da14427e7887035551b8c761a

Instead, `packed` will work:
```rust
#[packed]
type BBI {
  bool_1: bool, // align 1
  bool_2: bool, // align 1
  int: i32, // align 4
}
```

### Padding the type
```rust
type BBI {
  bool_1: bool, // align 1
  bool_2: bool, // align 1
  #[address(4)]
  int: i32, // align 4
}
```

## Vec4
```rust
#[align(16)]
type Vec4 {
  data: [f32; 4],
}
```
will generate a 16-aligned type in the backend. This will also propagate to other types using it:
```rust
type MyCoolType {
  vec1: Vec4,
  value: f32,
}
```
will require an alignment of 16 (due to `Vec4`), and a size of 32 (due to needing to be a multiple of alignment):
```rust
#[align(16), size(32)]
type MyCoolType {
  vec1: Vec4,
  value: f32,
}
```

## External type
```rust
#[align(16)]
extern type MyAlignedType;

type TestType {
  aligned: MyAlignedType,
}
```
The `TestType` will need to be aligned to 16 to match:
```rust
#[align(16)]
type TestType {
  aligned: MyAlignedType,
}
```

---

See also #15, which this will probably resolve.

**Comment by SK83RJOSH** [comment]
Ship it
